var timeAct=360; timeIni=360; timeBon=0;
var successes=0; successesMax=5; attempts=0; attemptsMax=5;
var score=0; scoreMax=5; scoreInc=1; scoreDec=1
var typeGame=0;
var tiTime=false;
var tiTimeType=0;
var tiButtonTime=true;
var textButtonTime="Comenzar";
var tiSuccesses=false;
var tiAttempts=true;
var tiScore=false;
var startTime;
var colorBack="#FFFDFD"; colorButton="#91962F"; colorText="#000000"; colorSele="#FF8000";
var goURLNext=false; goURLRepeat=false;tiAval=false;
var scoOk=0; scoWrong=0; scoOkDo=0; scoWrongDo=0; scoMessage=""; scoPtos=10;
var fMenssage="Verdana, Geneva, sans-serif";
var fActi="Verdana, Geneva, sans-serif";
var fEnun="Verdana, Geneva, sans-serif";
var timeOnMessage=5; messageOk="FELICIDADES"; messageTime=""; messageError="ERROR"; messageErrorG="ERROR"; messageAttempts=""; isShowMessage=false;
var urlOk=""; urlTime=""; urlError=""; urlAttempts="";
var goURLOk="_blank"; goURLTime="_blank"; goURLAttempts="_blank"; goURLError="_blank"; 
borderOk="#008000"; borderTime="#FF0000";borderError="#FF0000"; borderAttempts="#FF0000";
var wordsGame="ZnRmcmFzZXNz"; wordsStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function giveZindex(typeElement){var valueZindex=0; capas=document.getElementsByTagName(typeElement);
for (i=0;i<capas.length;i++){if (parseInt($(capas[i]).css("z-index"),10)>valueZindex){valueZindex=parseInt($(capas[i]).css("z-index"),10);}}return valueZindex;}
var words=["VHJpZm9zZmF0byBkZSBBZGVub3NpbmE=","Q2hhcmxlcyBSb2JlcnQgRGFyd2lu","SmVhbiBCYXB0aXN0ZSBMYW1hcmNr","QXBhcmF0byBkZSBHb2xnaQ==","VGVqaWRvIGVwaXRlbGlhbA=="];imaW=["ATP-e1539724904881.jpg","Charles_Darwin_1880.jpg","lamarck.jpg","aparato_de_golgi_definicion_y_funcion_3760_600_square.jpg","180px-Simple_columnar_epithelium_tissue.svg.png"];queW=["Es la molécula portadora de la energía primaria para todas las formas de vida","Es el científico más influyente de los que plantearon la idea de la evolución biológica a través de la selección natural","Es el primer naturalista que formula una teoría explicativa sobre los procesos evolutivos en el siglo XIX y es el primero en utilizar el término de biología","Su función es la segregación y maduración de proteínas","Recubre las superficies exteriores de los órganos internos y las superficies interiores de tubos y cavidades"];altW=["","","","",""];c=[23,21,21,16,16];
var auW=["","","","",""];
var actMaxWidth="600"; actMaxHeight="300";indexG=0;profG=0;dirMedia="ftfrasess_resources/media/"; textBNext="";
var wordsG=[];imageW=[];questionW=[];audioW=[];cG=[];alterW=[];
colorText="#2B2B2B";colorButton="#858B00";colorBack="#FFFFFF";colorSele="#F8F5D7";goURLNext=true;
fMenssage="Verdana, Geneva, sans-serif";fActi="Verdana, Geneva, sans-serif";fEnun="Verdana, Geneva, sans-serif";
